import CrouzeixConjecture

#check @CrouzeixConjecture.CanonicalParallelOrientedRadialBoundaryStatement
#check @CrouzeixConjecture.PositivePeriodicRadialData
#check @CrouzeixConjecture.PositivePeriodicRadialData.OrientedRadialConvexBoundary
#check @CrouzeixConjecture.numericalRange_convex
#check @CrouzeixConjecture.IsPositiveRealCompletion
#check @CrouzeixConjecture.PositiveRealCompletionStatement
#check @CrouzeixConjecture.positiveRealCompletionStatement
#check @CrouzeixConjecture.SimpleDiagonalization.functionEval
#check @CrouzeixConjecture.finite_type_sampling_quadratic_nonneg
#check @CrouzeixConjecture.completionSamplePoint
#check @CrouzeixConjecture.completionSampleCoefficient_quadratic_nonneg_of_positiveKernel
#check @CrouzeixConjecture.norm_completionDiagonalizableMatrix_le_two_of_positiveKernelModel
#check @CrouzeixConjecture.exists_completionDiagonalCorrection
#check @CrouzeixConjecture.exists_completionKernelModel_of_isPositiveRealCompletion
#check @CrouzeixConjecture.gramian_mulVec_eq_of_mulVec_eq_zero
#check @CrouzeixConjecture.gramian_four_sub_one_sub_first_posSemidef
#check @CrouzeixConjecture.PositivePeriodicRadialData.RadialConvexDomain.integral_holomorphic_cauchy
#check @CrouzeixConjecture.PositivePeriodicRadialData.RadialConvexDomain.integral_holomorphic_cauchy_resolvent_of_simpleDiagonalization
#check @CrouzeixConjecture.HasParametricPowerCauchyFormula
#check @CrouzeixConjecture.HasParametricPowerCauchyFormula.mass_eq_one
#check @CrouzeixConjecture.exists_positiveRealCompletion_of_parametricPowerCauchy
#check @CrouzeixConjecture.norm_le_two_of_parametricPowerCauchy
#check @CrouzeixConjecture.PositivePeriodicRadialData.OrientedRadialConvexBoundary.hasParametricPowerCauchyFormula_of_holomorphic_of_simpleDiagonalization
#check @CrouzeixConjecture.PositivePeriodicRadialData.OrientedRadialConvexBoundary.norm_functionEval_le_two_of_holomorphic_of_simpleDiagonalization
#check @CrouzeixConjecture.PositivePeriodicRadialData.OrientedRadialConvexBoundary.parametricBoundaryIntegral_eq_functionEval
#check @CrouzeixConjecture.PositivePeriodicRadialData.OrientedRadialConvexBoundary.parametricBoundaryIntegral_eq_holomorphicMatrixEval
#check @CrouzeixConjecture.holomorphicMatrixEval_polynomial
#check @CrouzeixConjecture.holomorphicMatrixEval_congr_on_neighborhood
#check @CrouzeixConjecture.holomorphicMatrixEval_add
#check @CrouzeixConjecture.holomorphicMatrixEval_neg
#check @CrouzeixConjecture.holomorphicMatrixEval_sub
#check @CrouzeixConjecture.holomorphicMatrixEval_mul
#check @CrouzeixConjecture.holomorphicCrouzeixBound
#check @CrouzeixConjecture.holomorphicMatrixEval_rational
#check @CrouzeixConjecture.holomorphicCrouzeixRationalBound
#check @CrouzeixConjecture.holomorphicCrouzeixPolynomialErrorBound
#check @CrouzeixConjecture.holomorphicCrouzeixRationalErrorBound
#check @CrouzeixConjecture.finiteRationalSpectralSetCorollary
#check @CrouzeixConjecture.crouzeixConjecture
#check @CrouzeixConjecture.crouzeixRationalSpectralSetCorollary
#check @CrouzeixConjecture.crouzeixRationalBound
#check @CrouzeixConjecture.jordanNilpotentTwo_attains_two
#check @CrouzeixConjecture.crouzeixConstantTwo_isLeast_finTwo
#check @CrouzeixConjecture.hilbertSpacePolynomialCrouzeix
#check @CrouzeixConjecture.spectrum_subset_closedOperatorNumericalRange
#check @CrouzeixConjecture.operatorRationalEval_eq_num_mul_inverse_denom
#check @CrouzeixConjecture.hilbertSpaceRationalCrouzeix
#check @CrouzeixConjecture.hilbertSpaceRationalSpectralSet
#check @CrouzeixConjecture.ClosedOperatorNumericalRangeIsTwoSpectralSet
#check @CrouzeixConjecture.closedOperatorNumericalRange_isTwoSpectralSet
#check @CrouzeixConjecture.scaledQNumericalRange
#check @CrouzeixConjecture.qKappa
#check @CrouzeixConjecture.scaledQNumericalRange_eq_norm
#check @CrouzeixConjecture.qKappa_parameter_identity
#check @CrouzeixConjecture.qTau_div_eq_qKappa_expression
#check @CrouzeixConjecture.two_div_qKappa
#check @CrouzeixConjecture.scaledQNumericalRange_eq_qDiskUnion
#check @CrouzeixConjecture.scaledQNumericalRange_antitone
#check @CrouzeixConjecture.stretchSimilarity_posDef
#check @CrouzeixConjecture.stretchSimilarity_inv
#check @CrouzeixConjecture.norm_stretch_product_le_half_add_inv
#check @CrouzeixConjecture.numericalRange_stretchSimilarity_subset_scaledQNumericalRange_complex
#check @CrouzeixConjecture.norm_le_max_one_div_of_uniform_stretch_mobius
#check @CrouzeixConjecture.rationalScaledQNumericalRangeBound_of_universal
#check @CrouzeixConjecture.rationalScaledQNumericalRangeBound_two
#check @CrouzeixConjecture.polynomialScaledQNumericalRangeBound_two
#check @CrouzeixConjecture.sharpScaledQNumericalRangeConstant
#check @CrouzeixConjecture.sharpRationalScaledQNumericalRangeBound
#check @CrouzeixConjecture.sharpPolynomialScaledQNumericalRangeBound
#check @CrouzeixConjecture.maxRationalModulusOnScaledQNumericalRange_X_jordanNilpotentTwo
#check @CrouzeixConjecture.sharpScaledQNumericalRangeConstant_isLeast_finTwo
#check @CrouzeixConjecture.sharpScaledQNumericalRangeConstant_isLeast_finTwo_complex

#print axioms CrouzeixConjecture.matrix_norm_eq_euclidean_operator_norm
#print axioms CrouzeixConjecture.inner_euclideanOperator_eq_star_dotProduct
#print axioms CrouzeixConjecture.euclideanOperator_conjTranspose
#print axioms CrouzeixConjecture.numericalRange_nonempty
#print axioms CrouzeixConjecture.isCompact_numericalRange
#print axioms CrouzeixConjecture.numericalRange_convex
#print axioms CrouzeixConjecture.numericalRange_perturbation
#print axioms CrouzeixConjecture.euclideanOperator_polynomialEval
#print axioms CrouzeixConjecture.matrixSpectrum_eq_operatorSpectrum
#print axioms CrouzeixConjecture.matrixSpectrum_subset_numericalRange
#print axioms CrouzeixConjecture.SimpleDiagonalization.functionEval
#print axioms CrouzeixConjecture.finite_type_sampling_quadratic_nonneg
#print axioms CrouzeixConjecture.completionSamplePoint_mem_openUnitDisk
#print axioms CrouzeixConjecture.completionP_denominator_ne_zero
#print axioms CrouzeixConjecture.completionP_isHermitian
#print axioms CrouzeixConjecture.completion_fourR_sub_twoP_apply
#print axioms CrouzeixConjecture.completion_mulVec_add_eq_zero
#print axioms CrouzeixConjecture.completion_PRX_substitution_identity
#print axioms CrouzeixConjecture.completionSampleCoefficient_quadratic_nonneg_of_positiveKernel
#print axioms CrouzeixConjecture.norm_completionDiagonalizableMatrix_le_two_of_positiveKernelModel
#print axioms CrouzeixConjecture.matrixHerglotzKernel_isPositiveMatrixKernelOn
#print axioms CrouzeixConjecture.exists_completionDiagonalCorrection
#print axioms CrouzeixConjecture.exists_completionKernelModel_of_isPositiveRealCompletion
#print axioms CrouzeixConjecture.gramian_mulVec_eq_of_mulVec_eq_zero
#print axioms CrouzeixConjecture.gramian_four_sub_one_sub_first_posSemidef
#print axioms CrouzeixConjecture.positiveRealCompletionStatement
#print axioms CrouzeixConjecture.isClosed_setOf_posSemidef
#print axioms CrouzeixConjecture.integral_posSemidef_of_ae
#print axioms CrouzeixConjecture.doubleLayerSupportMatrix_posSemidef_of_outwardBoundarySupport
#print axioms CrouzeixConjecture.doubleLayerResolvent_density_posSemidef
#print axioms CrouzeixConjecture.boundaryPhi_one
#print axioms CrouzeixConjecture.boundaryPhi_star
#print axioms CrouzeixConjecture.boundaryPhi_posSemidef
#print axioms CrouzeixConjecture.boundaryPhi_norm_le
#print axioms CrouzeixConjecture.cayleyBoundarySeriesTerm_hasSum
#print axioms CrouzeixConjecture.doubleLayerCayleySeries_analyticOnNhd
#print axioms CrouzeixConjecture.doubleLayerCayleySeries_rePart_posSemidef
#print axioms CrouzeixConjecture.matrixCayleyTransform_eq_two_resolvent_sub_one
#print axioms CrouzeixConjecture.isPositiveRealCompletion_of_direct_cayley_identity
#print axioms CrouzeixConjecture.parametricPositiveBoundaryDensity
#print axioms CrouzeixConjecture.two_smul_boundaryPhi_parametric_eq
#print axioms CrouzeixConjecture.parametricBoundaryFirstPartIntegral_cayley_eq
#print axioms CrouzeixConjecture.parametricBoundaryCompanion_mem_generatedAlgebra
#print axioms CrouzeixConjecture.parametricCayleyCompanion_mem_generatedAlgebra
#print axioms CrouzeixConjecture.parametric_direct_cayley_identity_of_powerCauchy
#print axioms CrouzeixConjecture.exists_positiveRealCompletion_of_parametricPowerCauchy
#print axioms CrouzeixConjecture.norm_le_two_of_parametricPowerCauchy
#print axioms CrouzeixConjecture.exists_hasDistinctEigenvalues_norm_sub_lt
#print axioms CrouzeixConjecture.tendsto_simpleSpectrumApproximation
#print axioms CrouzeixConjecture.parallelOuterDomain_data
#print axioms CrouzeixConjecture.tendsto_hausdorffDist_parallelOuterDomain_closure
#print axioms CrouzeixConjecture.convexProjection_variational
#print axioms CrouzeixConjecture.convexProjection_firm_nonexpansive
#print axioms CrouzeixConjecture.frontier_thickening_eq_infDist_level
#print axioms CrouzeixConjecture.hasFDerivAt_convexSquaredDistance
#print axioms CrouzeixConjecture.contDiff_one_convexSquaredDistance
#print axioms CrouzeixConjecture.contDiff_one_of_continuous_implicit_scalar
#print axioms CrouzeixConjecture.parallelRadialPoint_mem_frontier_thickening
#print axioms CrouzeixConjecture.outwardBoundarySupport_thickening
#print axioms CrouzeixConjecture.contDiff_one_parallelGaugeRadius
#print axioms CrouzeixConjecture.radialTangent_eq_I_mul_normal_mul_norm
#print axioms CrouzeixConjecture.parallelPositivePeriodicRadialData_normal_tangent_orthogonal
#print axioms CrouzeixConjecture.orientedRadialConvexBoundary_thickening
#print axioms CrouzeixConjecture.exists_orientedRadialConvexBoundary_thickening
#print axioms CrouzeixConjecture.PositivePeriodicRadialData.RadialConvexDomain.integral_tangent_div_point_sub
#print axioms CrouzeixConjecture.canonicalParallelOrientedRadialBoundaryStatement
#print axioms CrouzeixConjecture.eventually_simpleSpectrumApproximation_numericalRange_subset_open
#print axioms CrouzeixConjecture.PositivePeriodicRadialData.RadialConvexDomain.integral_holomorphic_cauchy
#print axioms CrouzeixConjecture.PositivePeriodicRadialData.RadialConvexDomain.integral_holomorphic_cauchy_resolvent_of_simpleDiagonalization
#print axioms CrouzeixConjecture.HasParametricPowerCauchyFormula.mass_eq_one
#print axioms CrouzeixConjecture.norm_le_two_of_parametricPowerCauchy
#print axioms CrouzeixConjecture.PositivePeriodicRadialData.OrientedRadialConvexBoundary.parametricBoundaryIntegral_eq_functionEval
#print axioms CrouzeixConjecture.PositivePeriodicRadialData.OrientedRadialConvexBoundary.parametricBoundaryIntegral_eq_holomorphicMatrixEval
#print axioms CrouzeixConjecture.PositivePeriodicRadialData.OrientedRadialConvexBoundary.hasParametricPowerCauchyFormula_of_holomorphic_of_simpleDiagonalization
#print axioms CrouzeixConjecture.PositivePeriodicRadialData.OrientedRadialConvexBoundary.norm_functionEval_le_two_of_holomorphic_of_simpleDiagonalization
#print axioms CrouzeixConjecture.tendsto_simpleSpectrumHolomorphicEval_of_differentiableOn_neighborhood
#print axioms CrouzeixConjecture.holomorphicMatrixEval_polynomial
#print axioms CrouzeixConjecture.holomorphicMatrixEval_congr_on_neighborhood
#print axioms CrouzeixConjecture.holomorphicMatrixEval_add
#print axioms CrouzeixConjecture.holomorphicMatrixEval_neg
#print axioms CrouzeixConjecture.holomorphicMatrixEval_sub
#print axioms CrouzeixConjecture.holomorphicMatrixEval_mul
#print axioms CrouzeixConjecture.holomorphicCrouzeixBound
#print axioms CrouzeixConjecture.holomorphicMatrixEval_rational
#print axioms CrouzeixConjecture.holomorphicCrouzeixRationalBound
#print axioms CrouzeixConjecture.holomorphicCrouzeixPolynomialErrorBound
#print axioms CrouzeixConjecture.holomorphicCrouzeixRationalErrorBound
#print axioms CrouzeixConjecture.finiteRationalSpectralSetCorollary
#print axioms CrouzeixConjecture.crouzeixConjecture
#print axioms CrouzeixConjecture.crouzeixRationalSpectralSetCorollary
#print axioms CrouzeixConjecture.crouzeixRationalBound
#print axioms CrouzeixConjecture.jordanNilpotentTwo_attains_two
#print axioms CrouzeixConjecture.crouzeixConstantTwo_isLeast_finTwo
#print axioms CrouzeixConjecture.hilbertSpacePolynomialCrouzeix
#print axioms CrouzeixConjecture.spectrum_subset_closedOperatorNumericalRange
#print axioms CrouzeixConjecture.operatorRationalEval_eq_num_mul_inverse_denom
#print axioms CrouzeixConjecture.hilbertSpaceRationalCrouzeix
#print axioms CrouzeixConjecture.hilbertSpaceRationalSpectralSet
#print axioms CrouzeixConjecture.closedOperatorNumericalRange_isTwoSpectralSet
#print axioms CrouzeixConjecture.scaledQNumericalRange_eq_norm
#print axioms CrouzeixConjecture.qKappa_parameter_identity
#print axioms CrouzeixConjecture.qTau_div_eq_qKappa_expression
#print axioms CrouzeixConjecture.two_div_qKappa
#print axioms CrouzeixConjecture.scaledQNumericalRange_eq_qDiskUnion
#print axioms CrouzeixConjecture.scaledQNumericalRange_antitone
#print axioms CrouzeixConjecture.stretchSimilarity_posDef
#print axioms CrouzeixConjecture.stretchSimilarity_inv
#print axioms CrouzeixConjecture.norm_stretch_product_le_half_add_inv
#print axioms CrouzeixConjecture.numericalRange_stretchSimilarity_subset_scaledQNumericalRange_complex
#print axioms CrouzeixConjecture.norm_le_max_one_div_of_uniform_stretch_mobius
#print axioms CrouzeixConjecture.rationalScaledQNumericalRangeBound_of_universal
#print axioms CrouzeixConjecture.rationalScaledQNumericalRangeBound_two
#print axioms CrouzeixConjecture.sharpRationalScaledQNumericalRangeBound
#print axioms CrouzeixConjecture.sharpPolynomialScaledQNumericalRangeBound
#print axioms CrouzeixConjecture.maxRationalModulusOnScaledQNumericalRange_X_jordanNilpotentTwo
#print axioms CrouzeixConjecture.qKappa_half_mem_scaledQNumericalRange_jordanNilpotentTwo
#print axioms CrouzeixConjecture.max_one_two_div_qKappa_le_of_rationalScaledQBoundOnFinTwo
#print axioms CrouzeixConjecture.sharpScaledQNumericalRangeConstant_isLeast_finTwo
#print axioms CrouzeixConjecture.sharpScaledQNumericalRangeConstant_isLeast_finTwo_complex
