import CrouzeixConjecture

#check @CrouzeixConjecture.MainTheoremStatement
#check @CrouzeixConjecture.CanonicalParallelDoubleLayerStatement
#check @CrouzeixConjecture.CanonicalParallelOrientedRadialBoundaryStatement
#check @CrouzeixConjecture.HasParametricPolynomialCauchyFormula
#check @CrouzeixConjecture.PositivePeriodicRadialData
#check @CrouzeixConjecture.PositivePeriodicRadialData.OrientedRadialConvexBoundary
#check @CrouzeixConjecture.mainTheoremStatement_of_canonicalParallelDoubleLayer
#check @CrouzeixConjecture.numericalRange_convex
#check @CrouzeixConjecture.positiveRealCompletionStatement
#check @CrouzeixConjecture.exists_analytic_completionDiagonalCorrection
#check @CrouzeixConjecture.rationalSpectralSetCorollary_of_mainTheorem
#check @CrouzeixConjecture.crouzeixConjecture_mainTheorem
#check @CrouzeixConjecture.crouzeixConjecture
#check @CrouzeixConjecture.crouzeixRationalSpectralSetCorollary
#check @CrouzeixConjecture.crouzeixRationalBound

#print axioms CrouzeixConjecture.matrix_norm_eq_euclidean_operator_norm
#print axioms CrouzeixConjecture.inner_euclideanOperator_eq_star_dotProduct
#print axioms CrouzeixConjecture.euclideanOperator_conjTranspose
#print axioms CrouzeixConjecture.numericalRange_nonempty
#print axioms CrouzeixConjecture.isCompact_numericalRange
#print axioms CrouzeixConjecture.numericalRange_convex
#print axioms CrouzeixConjecture.exists_maxPolynomialModulusOnNumericalRange
#print axioms CrouzeixConjecture.numericalRange_perturbation
#print axioms CrouzeixConjecture.euclideanOperator_polynomialEval
#print axioms CrouzeixConjecture.matrixSpectrum_eq_operatorSpectrum
#print axioms CrouzeixConjecture.matrixSpectrum_subset_numericalRange
#print axioms CrouzeixConjecture.polynomialEval_mem_generatedAlgebra
#print axioms CrouzeixConjecture.norm_normalizedLinearPerturbation_le_one
#print axioms CrouzeixConjecture.collisionParameters_finite
#print axioms CrouzeixConjecture.exists_small_injective_perturbation
#print axioms CrouzeixConjecture.tendsto_admissiblePerturbation_zero
#print axioms CrouzeixConjecture.completionP_denominator_ne_zero
#print axioms CrouzeixConjecture.completionP_isHermitian
#print axioms CrouzeixConjecture.completion_fourR_sub_twoP_apply
#print axioms CrouzeixConjecture.completion_mulVec_add_eq_zero
#print axioms CrouzeixConjecture.completion_PRX_substitution_identity
#print axioms CrouzeixConjecture.matrixHerglotzKernel_isPositiveMatrixKernelOn
#print axioms CrouzeixConjecture.exists_analytic_completionDiagonalCorrection
#print axioms CrouzeixConjecture.positiveRealCompletionStatement
#print axioms CrouzeixConjecture.isClosed_setOf_posSemidef
#print axioms CrouzeixConjecture.integral_posSemidef_of_ae
#print axioms CrouzeixConjecture.doubleLayerSupportMatrix_posSemidef_of_outwardBoundarySupport
#print axioms CrouzeixConjecture.doubleLayerResolvent_density_posSemidef
#print axioms CrouzeixConjecture.boundaryPhi_one
#print axioms CrouzeixConjecture.boundaryPhi_star
#print axioms CrouzeixConjecture.boundaryPhi_posSemidef
#print axioms CrouzeixConjecture.cayleyBoundarySeriesTerm_hasSum
#print axioms CrouzeixConjecture.doubleLayerCayleySeries_analyticOnNhd
#print axioms CrouzeixConjecture.doubleLayerCayleySeries_rePart_posSemidef
#print axioms CrouzeixConjecture.doubleLayerCayleySeries_isPositiveRealCompletion
#print axioms CrouzeixConjecture.hasDoubleLayerCompletionProvider_of_boundary_data
#print axioms CrouzeixConjecture.parametricPositiveBoundaryDensity
#print axioms CrouzeixConjecture.two_smul_boundaryPhi_parametricPolynomial_eq
#print axioms CrouzeixConjecture.parametricPolynomialCompanion_mem_generatedAlgebra
#print axioms CrouzeixConjecture.hasDoubleLayerCompletionProvider_of_parametricBoundary
#print axioms CrouzeixConjecture.norm_polynomialEval_le_two_mul_of_simpleSpectrum
#print axioms CrouzeixConjecture.tendsto_maxPolynomialModulusOnSet_of_outerApproximation
#print axioms CrouzeixConjecture.polynomialCrouzeixBound_of_simple_outer_approximants
#print axioms CrouzeixConjecture.exists_hasDistinctEigenvalues_norm_sub_lt
#print axioms CrouzeixConjecture.tendsto_simpleSpectrumApproximation
#print axioms CrouzeixConjecture.parallelOuterDomain_data
#print axioms CrouzeixConjecture.tendsto_hausdorffDist_parallelOuterDomain_closure
#print axioms CrouzeixConjecture.polynomialCrouzeixBound_of_parallelOuterDomains
#print axioms CrouzeixConjecture.polynomialCrouzeixBound_of_canonicalParallelOuterDomains
#print axioms CrouzeixConjecture.mainTheoremStatement_of_canonicalParallelDoubleLayer
#print axioms CrouzeixConjecture.convexProjection_variational
#print axioms CrouzeixConjecture.convexProjection_firm_nonexpansive
#print axioms CrouzeixConjecture.frontier_thickening_eq_infDist_level
#print axioms CrouzeixConjecture.hasFDerivAt_convexSquaredDistance
#print axioms CrouzeixConjecture.contDiff_one_convexSquaredDistance
#print axioms CrouzeixConjecture.contDiff_one_of_continuous_implicit_scalar
#print axioms CrouzeixConjecture.parallelRadialPoint_mem_frontier_thickening
#print axioms CrouzeixConjecture.outwardBoundarySupport_thickening
#print axioms CrouzeixConjecture.contDiff_one_parallelGaugeRadius
#print axioms CrouzeixConjecture.radialTangent_eq_I_mul_normal_mul_norm
#print axioms CrouzeixConjecture.parallelPositivePeriodicRadialData_normal_tangent_orthogonal
#print axioms CrouzeixConjecture.orientedRadialConvexBoundary_thickening
#print axioms CrouzeixConjecture.exists_orientedRadialConvexBoundary_thickening
#print axioms CrouzeixConjecture.PositivePeriodicRadialData.RadialConvexDomain.integral_tangent_div_point_sub
#print axioms CrouzeixConjecture.PositivePeriodicRadialData.RadialConvexDomain.integral_polynomial_cauchy
#print axioms CrouzeixConjecture.PositivePeriodicRadialData.RadialConvexDomain.integral_polynomial_cauchy_resolvent_of_simpleDiagonalization
#print axioms CrouzeixConjecture.PositivePeriodicRadialData.OrientedRadialConvexBoundary.hasParametricPolynomialCauchyFormula_of_simpleDiagonalization
#print axioms CrouzeixConjecture.PositivePeriodicRadialData.OrientedRadialConvexBoundary.hasDoubleLayerCompletionProvider_of_simpleDiagonalization
#print axioms CrouzeixConjecture.canonicalParallelOrientedRadialBoundaryStatement
#print axioms CrouzeixConjecture.canonicalParallelDoubleLayerStatement_of_orientedRadialBoundaries
#print axioms CrouzeixConjecture.crouzeixConjecture_mainTheorem
#print axioms CrouzeixConjecture.crouzeixConjecture
#print axioms CrouzeixConjecture.eventually_simpleSpectrumApproximation_numericalRange_subset_open
#print axioms CrouzeixConjecture.exists_polynomial_tendstoUniformlyOn_rationalScalarEval
#print axioms CrouzeixConjecture.tendsto_rationalMatrixEval_of_tendstoUniformlyOn_numericalRange
#print axioms CrouzeixConjecture.rationalSpectralSetCorollary_of_mainTheorem_of_numericalRange_convex
#print axioms CrouzeixConjecture.rationalSpectralSetCorollary_of_mainTheorem
#print axioms CrouzeixConjecture.crouzeixRationalSpectralSetCorollary
#print axioms CrouzeixConjecture.crouzeixRationalBound
